### ISSUE TITLE
Get marc4j into maven central repo

### ISSUE THREAD

**Issue by billdueber** [marc4j/marc4j#35]
Just got this email; the DSpace folks are interested in a marc4j loader but (understandably) want the library to be in maven central. Anyone have any experience with this?
# 

Many thanks for the useful marc4j library - nice work!

Last year, we have made a contribution to the popular DSpace (www.dspace.org) digital repository platform (please see the JIRA issue at https://jira.duraspace.org/browse/DS-12276 and the corresponding pull request at github https://github.com/DSpace/DSpace/pull/46).
Some more information can be found here: https://wiki.duraspace.org/pages/viewpage.action?pageId=32481931

In this year’s contribution, we would like to extends our data loaders of our biblio-transformation framework (https://github.com/EKT/Biblio-Transformation-Engine) in order to include a MarcDataLoader. We are planning to do so by using your marc4j library.

Since DSpace is built with maven it is very important that any library that DSpace depends on is available at a public maven repository, and in particular in Maven Central. This would be great for all maven-based applications that use marc4j, since the latest version of the library will be available for their build.

If you are interested in this, the best thing would be that you initiate the procedure for uploading the marc4j jar file to the Maven Central.
Sonatype act as an intermediary to facilitate this uploading. Here are a couple of helpful links:

https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage+Guide
https://docs.sonatype.org/display/Repository/Uploading+3rd-party+Artifacts+to+The+Central+Repository

There is already an account for my organisation (EKT in Greece) and DSpace at Sonatype so we could certainly put the marc4j jar in that space, but I am guessing you would hope to see it being used in other contexts in which case it would make more sense if it were in its own space.

This issue is quite pressing for us, since it is very important for the feature we are contributing to the next release of DSpace which is going to take place in the following weeks, therefore it would be great if you would soon have feedback from your side on this.

Best Regards,

Kostas Stamatis
National Documentation Center, Greece

**Comment by darrenleeweber** [comment]
@ksclarke - could you provide documentation on how this repo was adapted to maven (in addition to the raw git diffs, of course)?  It would be interesting to see whether your `mavenized` branch could be replicated in this repo.  That is, if it constitutes just a few commits that could be routinely rebased on the master branch here, that may provide a strategy for regularly updating the master branch of this repo in a maven release.  As it is now, the freelib-marc4j fork seems to have substantially diverged from this repo (50 commits behind now).  The idea is something like:

```
git checkout master
git pull
git checkout -b maven
# add commits to mavenize the project - squash them as much as possible
mvn clean # etc to build and release to maven central (get that all working)
git push origin maven
```
Then when master moves forward, the maven update might look something like:
```
git checkout master
git pull
git checkout maven
git rebase master
# pray that it easily replays without annoying conflicts (or make them go away as they arise)
# do the maven thing to publish
git push origin maven
```

**Comment by ksclarke** [comment]
@darrenleeweber As you've noticed, my branch has diverged significantly from this upstream. I do track the upstream (this project) and copy over code that I want (usually in manual changes rather than cherry picking because of the formatting differences). I'm currently behind (I don't have any updates since Oct. 21st of this year - https://github.com/ksclarke/freelib-marc4j/issues/26).

Most of my changes have been formatting sorts of things (as I use Checkstyle across my projects). I have made a few functional changes to the way XML is processed/generated (my main interest with MARC4J).

My `mavenized` branch would be the cleanest example of how this project was converted to use Maven (I've made a few other packaging changes since then at the suggestion of @haschart). That branch has not been touched since the initial conversion and doesn't have all the reformatting changes and other changes that have occurred since then. It's, of course, though, very out of touch with the master branch here, too.

As for how to mavenize this project, I don't really have any suggestions other than what you'd find in the `mavenized` branch. When I forked I was more interested in copying down changes rather than copying them back up. Perhaps diffing it and a snapshot of this repo around that time would be the best view.

I think @haschart has experimented some with reconciling the formatting differences in a branch here (`freelib-formatting`) but he'd have to speak to that. I'd imagine that would be a substantial amount of work.

**Comment by haschart** [comment]
I don't think any changes have been committed to the `freelib-reformatting` branch, I had even forgot that I created it.   There is a more recently created `Reformatting` branch with one commit, but I haven't found any way to even semi-automate the process.   Thus far it seems to be a laborious manual process to carefully examine the changes and merge the result.

**Comment by darrenleeweber** [comment]
Unless there are fundamental differences of opinion or philosophy about formatting and maven, or unsurmountable technical problems, there could be a lot more to gain from constructive PRs on this main repo than forking/diverging entirely.  It may be some work to integrate, but it could be well worth it to avoid confusion about how to work with MARC in java.

It seems that work on a maven build can be separated from the formatting changes (or most of them). If the maven build option can be resolved first, that's a big win.  If the formatting changes can be resolved, there may be no reason for a fork.  It would be a pity to have a plethora of maven packages out there for marc4j, which implies a lot of wasted research to discover the differences and choose one or another to work with.  Please try to integrate work using constructive PRs.

**Comment by ksclarke** [comment]
At the time when my fork was just a pure Maven refactoring, I brought up the topic of it here and my understanding from the response was that there wasn't much interest in seeing a Maven refactoring (which is different from just getting MARC4J into Maven Central, for which I do think there is some interest). So, I proceeded off on my own (making other changes, major reformatting changes, etc.) I understand that having more than one MARC4J in Maven Central is less than ideal but I don't think there is much incentive at this point to do the large amount of work that would be required to re-integrate them. I think it would be much less work to write a Maven wrapper around Ant and put the MARC4J proper jar into Maven Central. That's somebody's itch to scratch. :-)

**Comment by haschart** [comment]
A new version 2.7.3  has been released at GitHub.   There are almost no substantive changes in the code.   There are massive changes in the formatting to make it consistent throughout and to bring it much closer to the freelib branch.   The version has also been pushed to the [Maven Central Repo](http://search.maven.org/#artifactdetails|org.marc4j|marc4j|2.7.3|jar)
