### ISSUE TITLE
Changing marcxml prefix to "marc"

### ISSUE THREAD

**Issue by yanyufish** [marc4j/marc4j#67]
Hi.

I need the MARCXML_NS_PREFIX to be changed from "marcxml" to "marc".  And based on https://www.loc.gov/standards/marcxml/xml/collection.xml , looks like the standard prefix for marcxml is "marc" not "marcxml". Could anyone address this issue?

Thanks.

**Comment by ksclarke** [comment]
I'm not an official marc4j person but the namespace prefix used should be completely irrelevant. When you're writing XML-based tools that read in MARCXML created by MARC4J you can use "marc" as your namespace prefix and it will still work (as long as your "marc" namespace prefix is mapped to the same URI as the "marcxml" one in the records). The namespace prefix is just a convenient mapping to the URI. The URI is what must be the same. If you're not using namespace-aware XML tools (which would require perhaps that the same namespace prefix be exactly the same) I'd suggest upgrading your tools to tools that are namespace aware.

**Comment by haschart** [comment]
I'm about to make a new release of the library.  If you can explain why you need this changed, perhaps something can be done.  However ksclarke is right that the prefix used shouldn't be relevant, as long as the namespace is used consistently.  I suppose if you were including the marcxml namespaced data in another xml document that already used the marcxml namespace for something else, you could have problems.

**Comment by yanyufish** [comment]
That's basically the problem. And the other xsl files I am using to modify my marcxml only looks for prefix "marc" which is the standard prefix. Could you please change that one line in Constants.java? I don't see what's bad about modifying code to make it standard.

**Comment by ksclarke** [comment]
I'd be fine if the project wants to use "marc" instead of "marcxml" for a namespace prefix (though neither one is really a "standard"), but XSL should be namespace aware. I'd be glad to take a look at your XSL and offer some assistance, if possible, if you'd like. When XSL looks at a namespace prefix it should be actually comparing the URIs.

**Comment by haschart** [comment]
Since adding the namespace to the marcxml output is a somewhat recent change drawn from ksclarke's fork of marc4j, and since he seems fine with changing the namespace prefix that is used.  I'll commit and push the change, and then if there are no subsequent objections. I'll create a release containing that changed code in the next few days.

**Comment by haschart** [comment]
The recent [Release 2.8.3](https://github.com/marc4j/marc4j/releases/tag/2.8.3) contains this change.
